from __future__ import annotations

import os

import oracledb


def main() -> None:
    wallet = "/opt/everithing_manager/config/oracle-wallet"
    connection = oracledb.connect(
        user=os.environ["ORACLE_USER"],
        password=os.environ["ORACLE_PASSWORD"],
        dsn=os.environ["ORACLE_DSN"],
        config_dir=wallet,
        wallet_location=wallet,
        wallet_password=os.environ["ORACLE_PASSWORD"],
    )
    cursor = connection.cursor()
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM USER_TABLES
        WHERE TABLE_NAME = 'EM_AUTOMATIONS'
        """
    )
    exists = cursor.fetchone()[0]
    print(f"TABLE_EXISTS {exists}")

    if exists == 0:
        cursor.execute(
            """
            CREATE TABLE EM_AUTOMATIONS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TEMPLATE_KEY VARCHAR2(100) NOT NULL,
                TEMPLATE_NAME VARCHAR2(255) NOT NULL,
                SCHEDULE_KEY VARCHAR2(100) NOT NULL,
                STATUS VARCHAR2(50) DEFAULT 'ACTIVE' NOT NULL,
                CREATED_BY_USER_ID NUMBER,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                LAST_RUN_AT TIMESTAMP,
                NEXT_RUN_AT TIMESTAMP,
                CONSTRAINT EM_UQ_AUTOMATIONS_TEMPLATE UNIQUE (TEMPLATE_KEY),
                CONSTRAINT EM_FK_AUTOMATIONS_CREATED_BY FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES EM_USERS (ID)
            )
            """
        )
        connection.commit()
        print("TABLE_CREATED")
    else:
        print("MIGRATION_SKIPPED_ALREADY_EXISTS")

    cursor.close()
    connection.close()


if __name__ == "__main__":
    main()
