from __future__ import annotations

import os

import oracledb


def main() -> None:
    wallet = "/opt/everithing_manager/config/oracle-wallet"
    connection = oracledb.connect(
        user=os.environ["ORACLE_USER"],
        password=os.environ["ORACLE_PASSWORD"],
        dsn=os.environ["ORACLE_DSN"],
        config_dir=wallet,
        wallet_location=wallet,
        wallet_password=os.environ["ORACLE_PASSWORD"],
    )
    cursor = connection.cursor()
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM USER_TABLES
        WHERE TABLE_NAME = 'EM_MANAGED_BOTS'
        """
    )
    table_exists = cursor.fetchone()[0]
    print(f"TABLE_EXISTS {table_exists}")

    if table_exists == 0:
        cursor.execute(
            """
            CREATE TABLE EM_MANAGED_BOTS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                BOT_USERNAME VARCHAR2(255) NOT NULL,
                DISPLAY_NAME VARCHAR2(255),
                HEALTHCHECK_URL VARCHAR2(1000),
                ACTION_URL VARCHAR2(1000),
                STATUS VARCHAR2(50) DEFAULT 'UNKNOWN' NOT NULL,
                NOTES CLOB,
                CREATED_BY_USER_ID NUMBER,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                LAST_CHECKED_AT TIMESTAMP,
                CONSTRAINT EM_UQ_MANAGED_BOTS_USERNAME UNIQUE (BOT_USERNAME),
                CONSTRAINT EM_FK_MANAGED_BOTS_CREATED_BY FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES EM_USERS (ID)
            )
            """
        )
        cursor.execute(
            "CREATE UNIQUE INDEX EM_IDX_MANAGED_BOTS_USERNAME ON EM_MANAGED_BOTS (BOT_USERNAME)"
        )
        connection.commit()
        print("TABLE_CREATED")
        cursor.close()
        connection.close()
        return

    cursor.execute(
        """
        SELECT COUNT(*)
        FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = 'EM_MANAGED_BOTS'
          AND COLUMN_NAME = 'ACTION_URL'
        """
    )
    exists = cursor.fetchone()[0]
    print(f"COLUMN_EXISTS {exists}")

    if exists == 0:
        cursor.execute("ALTER TABLE EM_MANAGED_BOTS ADD (ACTION_URL VARCHAR2(1000))")
        connection.commit()
        print("MIGRATION_APPLIED")
    else:
        print("MIGRATION_SKIPPED_ALREADY_EXISTS")

    cursor.close()
    connection.close()


if __name__ == "__main__":
    main()
