-- Run this script as an admin user in the same shared Oracle database
-- that already hosts your other websites and bots.
-- Replace the placeholder password before execution.

CREATE USER EVERYTHING_MANAGER_APP IDENTIFIED BY "CHANGE_ME_STRONG_PASSWORD";

GRANT CREATE SESSION TO EVERYTHING_MANAGER_APP;
GRANT CREATE TABLE TO EVERYTHING_MANAGER_APP;
GRANT CREATE VIEW TO EVERYTHING_MANAGER_APP;
GRANT CREATE SEQUENCE TO EVERYTHING_MANAGER_APP;
GRANT CREATE PROCEDURE TO EVERYTHING_MANAGER_APP;
GRANT UNLIMITED TABLESPACE TO EVERYTHING_MANAGER_APP;

ALTER USER EVERYTHING_MANAGER_APP DEFAULT TABLESPACE DATA;
ALTER USER EVERYTHING_MANAGER_APP QUOTA UNLIMITED ON DATA;

-- Optional:
-- GRANT CREATE TRIGGER TO EVERYTHING_MANAGER_APP;
-- GRANT CREATE TYPE TO EVERYTHING_MANAGER_APP;

-- After connecting as EVERYTHING_MANAGER_APP, run:
-- @sql/001_init_em_core.sql
